tasks:
  - name: Install Minimamba
    before: |
      echo "Starting process"
    init: |
      curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
      bin/micromamba env create -f environment.yml -y
      bin/micromamba activate cpp
      bin/micromamba shell init
    command: |
      bin/micromamba shell init
      exec bash
  - name: Set up Jupyter Lab
    command: |
      jupyter server --generate-config
      echo "c.ServerApp.allow_remote_access = True" >> ~/.jupyter/jupyter_server_config.py
      echo "c = get_config()" >> ~/.jupyter/jupyter_server_config.py
      echo "c.LabApp.collaborative = True" >> ~/.jupyter/jupyter_server_config.py
      echo "c.ServerApp.allow_origin = '*'" >> ~/.jupyter/jupyter_server_config.py
      echo "c.ServerApp.token = ''" >> ~/.jupyter/jupyter_server_config.py

  

    
github:
  prebuilds:
    branches: true

ports:
  - name: Jupyter Lab
    description: The Default Jupyter Server Port
    port: 8888-8891
    visibility: public
    onOpen: open-browser

vscode:
  extensions:
    - mechatroner.rainbow-csv
    - akosyakov.gitpod-monitor